INSERT INTO adresa (nume_locatie_id, nume)
VALUES (1, 'Munte'),
(2, 'Munte'),
(3, 'Munte'),
(4, 'Munte'),
(5, 'Apa'),
(6, 'Pamant'),
(7, 'Apa'),
(8, 'Munte'),
(9, 'Munte'),
(10, 'Aer'),
(11, 'Aer'),
(12, 'Apa'),
(13, 'Apa'),
(14, 'Sfoara'),
(15, 'Sfoara'),
(16, 'Aer'),
(17, 'Pamant'),
(18, 'Pamant'),
(19, 'Aer'),
(20, 'Pamant')