INSERT INTO nume_locatie (oras_id, nume)
VALUES (1, 'Partie de ski'),
(2, 'Partie de ski'),
(3, 'Partie de ski'),
(4, 'Partie de ski'),
(4, 'Traseu Kayak'),
(5, 'Traseu ATV'),
(5, 'Traseu Kayak'),
(6, 'Partie de ski'),
(6, 'Partie de ski'),
(7, 'Pista de zbor'),
(7, 'Pista de zbor'),
(8, 'Traseu Kayak'),
(8, 'Traseu Kayak'),
(9, 'Locatie Bungee'),
(10, 'Locatie Bungee'),
(10, 'Pista de zbor'),
(11, 'Traseu ATV'),
(11, 'Traseu ATV'),
(12, 'Pista de zbor'),
(12, 'Traseu ATV')